name: CI

on:
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle
        
    - name: Make Gradle Wrapper executable
      run: chmod +x gradlew
      
    - name: Build and Test with Gradle
      run: ./gradlew build testDebug
      
    - name: Run Android Tests
      run: ./gradlew connectedCheck
      
    - name: Run Lint
      run: ./gradlew lintDebug
      
    - name: Package APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
